name 'build_agent'
maintainer 'Stefan Freitag'
maintainer_email 'stefan.freitag@udo.edu'
license 'Apache-2.0'
description 'Installs/Configures build_agent'
long_description 'Installs/Configures build_agent'
version '0.1.3'
chef_version '>= 13.6.4' if respond_to?(:chef_version)
issues_url 'https://github.com/stefanfreitag/build_agent/issues'
source_url 'https://github.com/stefanfreitag/build_agent'
supports 'centos', '>=6.9'
